package com.hackerrank.boyuanzhang;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Sha256 {

	public static String getSHA256(String input) {

		try {
			// Static getInstance method is called with hashing SHA
			MessageDigest md = MessageDigest.getInstance("SHA-256");

			// digest() method called
			// to calculate message digest of an input
			// and return array of byte
			byte[] messageDigest = md.digest(input.getBytes());
			System.out.println("messageDigest: " + messageDigest.toString());

			// Convert byte array into signum representation
			BigInteger no = new BigInteger(1, messageDigest);
			System.out.println(no);

			// Convert message digest into hex value
			String hashtext = no.toString(16);

			while (hashtext.length() < 64) {
				hashtext = "0" + hashtext;
			}

			return hashtext;
		}

		// For specifying wrong message digest algorithms
		catch (NoSuchAlgorithmException e) {
			System.out.println("Exception thrown" + " for incorrect algorithm: " + e);
			return null;
		}
	}

	// Driver code
	public static void main(String args[]) throws NoSuchAlgorithmException {
		System.out.println("HashCode Generated by SHA-256 for:");

		String s2 = "HelloWorld";
		System.out.println("\n" + s2 + " : " + getSHA256(s2));
	}
}
